name: Makefiles

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  GCC-build:
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'ubuntu-latest' ]
        GCC: [ '14', '15' ]

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC & libraries
      run: sudo apt update && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install gfortran-${{ matrix.GCC }} libsdl2-dev

    - name: Build
      run: FC=gfortran-${{ matrix.GCC }} make all
