name: xmake

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  GCC-build:
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image: [ 'ubuntu-latest' ]
        GCC: [ '12', '14' ]

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC & libraries
      run: sudo apt update && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install gfortran-${{ matrix.GCC }} libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libgl libglu1-mesa xmake

    - name: Build
      run: FC=gfortran-${{ matrix.GCC }} xmake
